apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.yml: |
    path.config: /usr/share/logstash/config/pipeline
  pipeline.conf: |
    input {
      file {
        path => "/var/log/*.log"
        start_position => "beginning"
      }
    }
    output {
      stdout { codec => rubydebug }
    }

