apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ilmioreplicaset
  labels:
    app: web
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        environment: dev
        app: web
        region: EU
    spec:
      containers:
      - name: flask
        image: digitalocean/flask-helloworld


